# Setup
title:               Excalibur-SLE
tagline:             'Exascale HPC for System Level Engineering'
description:         'An Excalibur Design and Development Working Group'
url:                 https://chrisrichardson.github.io/lanyon
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.2.0
# google_analytics_id:
github:
  repo: https://github.com/excalibur-sle
